/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };